### ISSUE TITLE
Update Rest Docs to 1.2.0

### ISSUE THREAD

**Issue by psamsotha** [RESTDocsEXT/restdocsext-jersey#6]
Todo

- [x] Update tests to accommodate for default line breaks in cURL snippets
- [x] Update and test examples

**Comment by ghost** [comment]
Hey @psamsotha, do you have any active plans on upgrading to a more recent spring restdocs version? I see that [version 2](https://projects.spring.io/spring-restdocs/) is out. Is this something you would welcome a PR on?

**Comment by psamsotha** [comment]
@stiancognite Yea, if you want to make that work, that would be great. Hopefully it won't be too difficult. Let me know what you decide to do.
